modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/CreeperHost/PolyLib/issues"
license = "Insert License Here"

[[mods]]
modId = "polylib"
version = "${version}"
displayName = "PolyLib"
authors = "CreeperHost"
description = '''
'''
#logoFile = ""

[[dependencies.polylib]]
modId = "forge"
mandatory = true
versionRange = "[41.0.64,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.polylib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.polylib]]
modId = "architectury"
mandatory = true
versionRange = "[3.8.29,)"
ordering = "AFTER"
side = "BOTH"
